= all twiliofaces inject annotations

Twilio makes HTTP requests to your application just like a regular web browser. By including parameters and values in its requests, Twilio sends data to your application that you can act upon before responding. 
You can configure the URLs and HTTP Methods Twilio uses to make its requests via the account portal or using 
the REST API.
You can inject, in your CDI bean, a twilio request param  using the corresponding annotation:

----

@Named
@RequestScoped
public SimpleController {

@Inject
@ApiVersion
String apiVersion

....

}

----

For more information about single param, read:
http://www.twilio.com/docs/api/twiml/twilio_request


== configuration annotations

. ApiVersion
. ApplicationSid	
. TwilioClientToken	
. TwilioNumber		
. TwilioSid		
. TwilioToken


== notification annotations
		
. AccountSid		
. CallSid		
. CallStatus		
. CallerName		
. Digits		
. Direction		
. ForwardedFrom		
. From		
. FromCity		
. FromCountry		
. FromState		
. FromZip		
. RecordingDuration		
. RecordingSid		
. RecordingUrl		
. SmsStatus		
. To		
. ToCity		
. ToCountry		
. ToState		
. ToZip		
. TranscriptionSid		
. TranscriptionStatus		
. TranscriptionText		
. TranscriptionUrl		
. TwilioSignature

== twilio scope annotation

. TwilioScope

== sip annotations

. DialSipCallId		
. DialSipHeader		
. DialSipHeader_		
. DialSipResponseCode		
. SipCallId		
. SipHeader

== all request params annotation 

. TwilioRequestParams
