= all twiliofaces inject annotations

Twilio makes HTTP requests to your application just like a regular web browser. By including parameters and values in its requests, Twilio sends data to your application that you can act upon before responding. 
You can configure the URLs and HTTP Methods Twilio uses to make its requests via the account portal or using 
the REST API.
You can inject all twilio request params, in your CDI beans:

----

@Named
@RequestScoped
public SimpleController {

....

}

----

For more information about single param, read:
http://www.twilio.com/docs/api/twiml/twilio_request


== configuration

. ApiVersion

----

@Inject
@ApiVersion
String apiVersion

----

. ApplicationSid	
. TwilioClientToken	
. TwilioNumber		
. TwilioSid		
. TwilioToken


== notification
		
. AccountSid		
. CallSid		
. CallStatus		
. CallerName		
. Digits		
. Direction		
. ForwardedFrom		
. From		
. FromCity		
. FromCountry		
. FromState		
. FromZip		
. RecordingDuration		
. RecordingSid		
. RecordingUrl		
. SmsStatus		
. To		
. ToCity		
. ToCountry		
. ToState		
. ToZip		
. TranscriptionSid		
. TranscriptionStatus		
. TranscriptionText		
. TranscriptionUrl		
. TwilioSignature

== scope

. TwilioScope

== sip

. DialSipCallId		
. DialSipHeader		
. DialSipHeader_		
. DialSipResponseCode		
. SipCallId		
. SipHeader

== all request vars

. TwilioRequestParams
